# Generated by Django 2.2.5 on 2019-10-02 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 23, 36, 1, 499133)),
        ),
    ]
