# Generated by Django 2.2.5 on 2019-10-02 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0003_auto_20191002_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('black', 'Black')], default='green', max_length=6),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 2, 23, 43, 27, 85639)),
        ),
    ]
