# Generated by Django 2.2.5 on 2019-10-12 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0007_auto_20191012_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 12, 23, 39, 12, 875592)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
