# Generated by Django 2.2.5 on 2019-10-18 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaults', '0008_auto_20191012_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='featured',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Everwhere'), (2, 'Category-only')], default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 19, 0, 41, 8, 938040)),
        ),
    ]
